# Generated by Django 5.1.6 on 2025-02-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='time_management',
            new_name='working_time',
        ),
        migrations.RenameField(
            model_name='timemanagement',
            old_name='value',
            new_name='working_time',
        ),
    ]
